// Institution types & categories — sourced from All_Institute_Types.pdf
export type InstitutionType = { name: string; category: string };

export const INSTITUTION_TYPES: InstitutionType[] = [
  { name: "Primary School", category: "Schools" },
  { name: "Secondary School", category: "Schools" },
  { name: "Combined School", category: "Schools" },
  { name: "Intermediate School", category: "Schools" },
  { name: "Special Needs Education", category: "Schools" },
  { name: "School Of Skills", category: "Schools" },
  { name: "ECD", category: "Schools" },
  { name: "Hospital School", category: "Schools" },
  { name: "Libraries", category: "Public Offices" },
  { name: "Department of Correctional Services", category: "Public Offices" },
  { name: "Thusong Service Centre", category: "Public Offices" },
  { name: "Police Academies and Stations", category: "Public Offices" },
  { name: "Local Governments (Municipalities)", category: "Public Offices" },
  { name: "Regional Governments (Municipalities)", category: "Public Offices" },
  { name: "Provincial Governments", category: "Public Offices" },
  { name: "National Government Agencies", category: "Public Offices" },
  { name: "SOE's", category: "Public Offices" },
  { name: "Embassies", category: "Public Offices" },
  { name: "Private Registered Colleges", category: "Private Higher Education" },
  { name: "TVET", category: "Private Higher Education" },
  { name: "Private Higher Education Institutions", category: "Private Higher Education" },
  { name: "Nursing Educational Institution", category: "Private Higher Education" },
  { name: "Universities", category: "Mixed Higher Education" },
  { name: "University Of Technology", category: "Mixed Higher Education" },
  { name: "Professional Institutions", category: "Private Offices" },
  { name: "NGO", category: "Private Offices" },
  { name: "NPO", category: "Private Offices" },
  { name: "NPC", category: "Private Offices" },
  { name: "Sport Bodies", category: "Private Offices" },
  { name: "Trusts and Foundations", category: "Private Offices" },
  { name: "Financial Bodies", category: "Private Offices" },
  { name: "Gaffney's Business Contacts", category: "Private Offices" },
  { name: "Teacher Bodies", category: "Public Offices" },
  { name: "Hospitals", category: "Mixed Offices" },
  { name: "Clinics", category: "Mixed Offices" },
  { name: "Day Hospitals", category: "Mixed Offices" },
  { name: "Maritime", category: "Mixed Offices" },
  { name: "Aviation", category: "Mixed Offices" },
  { name: "Agriculture", category: "Mixed Offices" },
  { name: "R&D", category: "Mixed Offices" },
  { name: "Health", category: "Mixed Offices" },
  { name: "Aerospace", category: "Mixed Offices" },
  { name: "Manufacturing/Fabrication", category: "Mixed Offices" },
  { name: "Bio", category: "Mixed Offices" },
  { name: "Renewables", category: "Mixed Offices" },
  { name: "Energy", category: "Mixed Offices" },
  { name: "United Nations Agencies", category: "International Offices" },
  { name: "EU Agencies", category: "International Offices" },
  { name: "Commission for Conciliation, Mediation and Arbitration (CCMA)", category: "Unions - Parties" },
  { name: "CONSAWU - Confederation of South African Workers' Unions", category: "Unions - Parties" },
  { name: "COSATU - Congress of South African Trade Unions", category: "Unions - Parties" },
  { name: "FEDUSA - Federation of Unions of South Africa", category: "Unions - Parties" },
  { name: "FOSATU - Federation of South African Trade Unions", category: "Unions - Parties" },
  { name: "ITUC - International Trade Union Confederation", category: "Unions - Parties" },
  { name: "ILO - International Labour Organization", category: "Unions - Parties" },
  { name: "NACTU - National Council of Trade Unions", category: "Unions - Parties" },
  { name: "NEDLAC - National Economic Development and Labour Council", category: "Unions - Parties" },
  { name: "NEHAWU - National Education, Health and Allied Workers' Union", category: "Unions - Parties" },
  { name: "NUM - National Union of Mineworkers", category: "Unions - Parties" },
  { name: "SACCOLA - South African Committee on Labour Affairs", category: "Unions - Parties" },
  { name: "SACP - South African Communist Party", category: "Unions - Parties" },
  { name: "SATLC - South African Trades and Labour Council", category: "Unions - Parties" },
  { name: "TAC - Treatment Action Campaign", category: "Unions - Parties" },
  { name: "UWUSA - United Workers' Union of South Africa", category: "Unions - Parties" },
  { name: "ULEMASA - Union for Local Employees in Missions Accredited to SA", category: "Unions - Parties" },
  { name: "Political Parties", category: "Unions - Parties" },
  { name: "South African Municipal Workers' Union (SAMWU)", category: "Unions - Parties" },
  { name: "Chemical, Energy, Paper, Printing, Wood and Allied Workers' Union", category: "Unions - Parties" },
  { name: "Southern African Clothing and Textile Workers' Union", category: "Unions - Parties" },
  { name: "Communication Workers Union", category: "Unions - Parties" },
  { name: "South African Commercial, Catering and Allied Workers Union", category: "Unions - Parties" },
  { name: "South African State and Allied Workers' Union (SASAWU)", category: "Unions - Parties" },
  { name: "Food and Allied Workers Union", category: "Unions - Parties" },
  { name: "South African Agricultural Plantation and Allied Workers Union", category: "Unions - Parties" },
  { name: "Democratic Nursing Organisation of South Africa (DENOSA)", category: "Unions - Parties" },
  { name: "National Union of Metalworkers of South Africa (NUMSA)", category: "Unions - Parties" },
  { name: "Police and Prisons Civil Rights Union (POPCRU)", category: "Unions - Parties" },
  { name: "South African Democratic Teachers Union (SADTU)", category: "Unions - Parties" },
  { name: "National Union of Food, Beverage, Wine, Spirit and Allied Workers", category: "Unions - Parties" },
  { name: "South African Chemical Workers' Union (SACWU)", category: "Unions - Parties" },
  { name: "South African Private Security Workers' Union (SAPSWU)", category: "Unions - Parties" },
  { name: "Public Servants Association of South Africa (PSA)", category: "Unions - Parties" },
  { name: "Banking Sector ETA (BANKSETA)", category: "Unions - Parties" },
  { name: "Construction ETA (CETA)", category: "Unions - Parties" },
  { name: "Culture, Arts, Tourism, Hospitality & Sport ETA (CATHSSETA)", category: "Unions - Parties" },
  { name: "Education, Training & Development Practices SETA (ETDP SETA)", category: "Unions - Parties" },
  { name: "Energy and Water SETA (EWSETA)", category: "Unions - Parties" },
  { name: "Financial and Accounting Services SETA (FASSET)", category: "Unions - Parties" },
  { name: "Food and Beverages Manufacturing SETA (FOODBEV)", category: "Unions - Parties" },
  { name: "Forest Industries SETA (FIETA)", category: "Unions - Parties" },
  { name: "Health and Welfare SETA (HWSETA)", category: "Unions - Parties" },
  { name: "Local Government SETA (LGSETA)", category: "Unions - Parties" },
  { name: "Manufacturing, Engineering & Related Services ETA (MERSETA)", category: "Unions - Parties" },
  { name: "Media, Information & Communication Technologies SETA (MICTSETA)", category: "Unions - Parties" },
  { name: "Mining Qualifications Authority (MQA)", category: "Unions - Parties" },
  { name: "Arbitration Foundation of Southern Africa (AFSA)", category: "Unions - Parties" },
  { name: "Confederation of Employers of South Africa (Cofesa)", category: "Unions - Parties" },
  { name: "Ditsela Workers' Education Institute", category: "Unions - Parties" },
  { name: "Public Service Co-ordinating Bargaining Council (PSCBC)", category: "Unions - Parties" },
  { name: "Cape Teachers' Professional Association (CTPA)", category: "Unions - Parties" },
  { name: "Health and Other Service Personnel Trade Union (HOSPERSA)", category: "Unions - Parties" },
  { name: "National Teachers Union (NATU)", category: "Unions - Parties" },
  { name: "National Professional Teachers' Association of SA (NAPTOSA)", category: "Unions - Parties" },
  { name: "National Public Service Workers Union (NPSWU)", category: "Unions - Parties" },
  { name: "National Union of Public Service & Allied Workers (NUPSAW)", category: "Unions - Parties" },
  { name: "Public and Allied Workers Union of South Africa (PAWUSA)", category: "Unions - Parties" },
  { name: "Professional Educators Union (PEU)", category: "Unions - Parties" },
  { name: "Suid Afrikaanse Onderwysersunie (SAOU)", category: "Unions - Parties" },
  { name: "South African Medical Association (SAMA)", category: "Unions - Parties" },
];

export const INSTITUTION_TYPES_BY_CATEGORY = INSTITUTION_TYPES.reduce<Record<string, InstitutionType[]>>((acc, t) => {
  (acc[t.category] ||= []).push(t);
  return acc;
}, {});

export const INSTITUTION_CATEGORIES = Object.keys(INSTITUTION_TYPES_BY_CATEGORY);
